name: .NET Core

on:
  push:
    branches: [ master, dev ] # batch is not available yet
  pull_request:
    branches: [ master, dev]

jobs:
  build_and_test:
    runs-on: [ubuntu-16.04]

    steps:
    # - if: ${{env.RunTestsOnly}} == 'false'
    - uses: actions/checkout@v2
    - name: Setup .NET Core # could ommit/get latest
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build LoRa Engine
      run: dotnet build --configuration $(buildConfiguration) ./LoRaEngine/LoRaEngine.sln
    - name: Build C# Samples/DecoderSample
      run: dotnet build --configuration $(buildConfiguration) ./Samples/DecoderSample
    - name: Build LoRa Simulator
      run: dotnet build --configuration $(buildConfiguration) ./LoRaEngine/modules/LoRaSimulator/LoRaSimulator.sln
